import java.util.concurrent.TimeUnit;

public class Intro extends RedKeepandDrogo{
    public static void intro() throws InterruptedException {
        System.out.println("                                                                                ");
        System.out.println("                                                                                ");
        System.out.println("                                         .. .:OO,MMMMMMMI.                                ");
        TimeUnit.MILLISECONDS.sleep(50);
        System.out.println("                                   ....~:.NMNMMMMMMMMMMN .  .                             ");
        TimeUnit.MILLISECONDS.sleep(50);
        System.out.println("                            ... $MMMM.... ?MMMMDM+Z,8MMMN.ZMMMMO,....                     ");
        TimeUnit.MILLISECONDS.sleep(50);
        System.out.println("                          .,8MMMMMMMMMMMM,.~,.......+MMMD.. DMMMMMMM....                  ");
        TimeUnit.MILLISECONDS.sleep(50);
        System.out.println("                        ..,MMMMMMM:..NMMMM...     ,,MMMMM.MMMM ..NMMMMM=..                ");
        TimeUnit.MILLISECONDS.sleep(50);
        System.out.println("                       .OMMMMMMM . .. MMMM+ .... MMMMMM,. OMM . .MMM MMMNM ..             ");
        TimeUnit.MILLISECONDS.sleep(50);
        System.out.println("                       7  M,MM:...  . MMMM ...MNMMMMM.... .MMMNMMMMI .. MMMM ..           ");
        TimeUnit.MILLISECONDS.sleep(50);
        System.out.println("                     .........       .MMMMIMMMMMM,...  ..,:~+MMO, ...  ..MMMM=...         ");
        TimeUnit.MILLISECONDS.sleep(50);
        System.out.println("                 ..N,. . N.8M,.,......MMMMMMMM+., NMMMMMMMMMMMMMMMMM:......MMMM..         ");
        TimeUnit.MILLISECONDS.sleep(50);
        System.out.println("                 .ZD MMMMMMMMMMMMM8...MMMMMNZ.. ..MMMMMMMMMMMMMMMMMMMMMM,...MMMM,.        ");
        TimeUnit.MILLISECONDS.sleep(50);
        System.out.println("                  MMMMMMM ,..:MMMMMM=.MMMMMM.    ..=MMMMMMMMMMM.$MMMMMMMMMN. IMM77..      ");
        TimeUnit.MILLISECONDS.sleep(50);
        System.out.println("               .~7MMMMM      ....MMMMMMMMMM~ .    ..MMMMM....=?. . MMMMMMMMMM ZMM8,..     ");
        TimeUnit.MILLISECONDS.sleep(50);
        System.out.println("               ..MMMMM..      ....:MMMMMMMMMD:.... MMMMMMM,....OMM$..,..+MMMMM $MMM.      ");
        TimeUnit.MILLISECONDS.sleep(50);
        System.out.println("               .MMM+MM..  ..:=~8M..+MMMMMMMMMMMMMMMMMMM$7OO.,.MMMMMMM:.. ,MMMMM7+MM:      ");
        TimeUnit.MILLISECONDS.sleep(50);
        System.out.println("               .M$I.MM7....?MMMMMM..7MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.. MMMMMM7.M8      ");
        TimeUnit.MILLISECONDS.sleep(50);
        System.out.println("               .MM?...  ...$MMMMMM...=MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM..8MMMMMM ND      ");
        TimeUnit.MILLISECONDS.sleep(50);
        System.out.println("               .+MM. ... . ....MMMM. ..MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM ....MMMN.Z      ");
        TimeUnit.MILLISECONDS.sleep(50);
        System.out.println("               ..MM.IMMMMMMM....MMMM ......MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM... MMMM.       ");
        TimeUnit.MILLISECONDS.sleep(50);
        System.out.println("               . MM~MM.. ..MMMM?MM MMM,....MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM~. .MMMM.       ");
        TimeUnit.MILLISECONDS.sleep(50);
        System.out.println("               ...MMM .   ..MMM+?... MMMMM+MMMMMM:MMMMMMMMMMMMMMMMNN.DMMMMM .8MMMM.       ");
        TimeUnit.MILLISECONDS.sleep(50);
        System.out.println("                 .:MM,..  .+MM,. .   .,.?MMMMMMM..MMMMMMMMMMMMMMMMM..7MMMMM.,.MMM,.       ");
        TimeUnit.MILLISECONDS.sleep(50);
        System.out.println("                  ?MMMMMMMMM?$.  .. ...   .,IN7...MMMMMMMMMMMMMMMM. .MMMMMM.  MMM.        ");
        TimeUnit.MILLISECONDS.sleep(50);
        System.out.println("                  ..$MI..,.       MMMMM,. . ..    .+MMMMM .MMMMMMMN...8MMM~...MM..        ");
        TimeUnit.MILLISECONDS.sleep(50);
        System.out.println("                  ...MMM..      . MMMMMMM. ..  ....8MMMMM .MMMMMM:O..:MMMM...MM .         ");
        TimeUnit.MILLISECONDS.sleep(50);
        System.out.println("                 . .,MMMM     ..Z. ..NMMMMMMMMMMMMMMMMMM.MMMMMMM~ .MMMMM..:M$...         ");
        TimeUnit.MILLISECONDS.sleep(50);
        System.out.println("                       ..MM8 ...       .MM  .        .....MMMMM$..MMMMMM..M8.             ");
        TimeUnit.MILLISECONDS.sleep(50);
        System.out.println("                      ... ODMM? .      ,,N,.        . .?MMMMM?.....MMM..M8..              ");
        TimeUnit.MILLISECONDS.sleep(50);
        System.out.println("                           ..MMMMM$ ,... .... ..... DMMMMN8M. .,.$MM..~...                ");
        TimeUnit.MILLISECONDS.sleep(50);
        System.out.println("                              .~MMMMMMMMMMMMMMMMMMMMMN?M=..IMNMMMN ....                   ");
        TimeUnit.MILLISECONDS.sleep(50);
        System.out.println("                              . . .,8MN~MMMM~~MMM.Z.,....+MMMM...                         ");
        TimeUnit.MILLISECONDS.sleep(50);
        System.out.println("                                       .  ..,..,:?DMMMMMM$...                             ");
        TimeUnit.MILLISECONDS.sleep(300);
        System.out.println("______  _____ ______   _   __ _____  _____ ______                     _  ______ ______  _____  _____  _____ ");
        System.out.println("| ___ \\|  ___||  _  \\ | | / /|  ___||  ___|| ___ \\                   | | |  _  \\| ___ \\|  _  ||  __ \\|  _  |");
        System.out.println("| |_/ /| |__  | | | | | |/ / | |__  | |__  | |_/ /   __ _  _ __    __| | | | | || |_/ /| | | || |  \\/| | | |");
        System.out.println("|    / |  __| | | | | |    \\ |  __| |  __| |  __/   / _` || '_ \\  / _` | | | | ||    / | | | || | __ | | | |");
        System.out.println("| |\\ \\ | |___ | |/ /  | |\\  \\| |___ | |___ | |     | (_| || | | || (_| | | |/ / | |\\ \\ \\ \\_/ /| |_\\ \\\\ \\_/ /");
        System.out.println("\\_| \\_|\\____/ |___/   \\_| \\_/\\____/ \\____/ \\_|      \\__,_||_| |_| \\__,_| |___/  \\_| \\_| \\___/  \\____/ \\___/ \n");
        TimeUnit.MILLISECONDS.sleep(300);
    }
}
